version: 0.2

env:
  variables:
    EXPECTED_KEY: $(git rev-parse origin/main)
    ACTUAL_KEY: $CODEBUILD_RESOLVED_SOURCE_VERSION

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      # install node.js
      - npm i -g npm@latest
      - npm pkg get engines.node | sed 's/"//g' | xargs n
      # install packages
      - npm ci
      # chrome
      - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      - apt-get -y update
      - apt-get -y install google-chrome-stable
  pre_build:
    commands:
      - npx storycap --serverCmd "npx start-storybook -p 6060 --ci" http://localhost:6060
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $(git rev-parse origin/main)
      - npm run reg-suit
